version: "3.8"

services:
  pgdb:
    image: postgres:13
    environment:
      POSTGRES_USER: test1
      POSTGRES_PASSWORD: test1
      POSTGRES_DB: news_crawled
    container_name: local_pgdb
    restart: always
    volumes:
      - "./news_crawled_test:/var/lib/postgresql/data:rw"
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: always
    ports:
      - "5050:80"